server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      routes:
#      - id: user-api
#        uri: lb://user-api/
#        predicates:
#        - Path=/api/user/**
#      - id: accounts-api
#        uri: http://localhost:8082/
#        predicates:
#        - Path=/api/accounts/**
#      - id: transaction-api
#        uri: http://localhost:8083/
#        predicates:
#        - Path=/api/transaction/**
#      - id: authentication-api
#        uri: http://localhost:8084/
#        predicates:
#        - Path=/login
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
jwt:
  secretkey: mysecretkey



